[default]
USERNAME = "in7hesky"
FLASK_DEBUG = false
SQLALCHEMY_DATABASE_URI = "sqlite:///site.db"

[development]
EXTENSIONS = ["flask_debugtoolbar:DebugToolbarExtension"]
FLASK_DEBUG = true
DEBUG_TB_ENABLED = true