[default]
FLASK_DEBUG = false
SQLALCHEMY_DATABASE_URI = "sqlite:///site.db"

[development]
EXTENSIONS = ["flask_debugtoolbar:DebugToolbarExtension"]
FLASK_DEBUG = true
DEBUG_TB_ENABLED = true
SQLALCHEMY_RECORD_QUERIES = true
DEBUG_TB_INTERCEPT_REDIRECTS = false